# Generated by Django 2.2.4 on 2022-09-28 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0002_show_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='descreption',
            field=models.TextField(default='To be added'),
        ),
    ]
